const fs=require('fs');
const R=(label,x,y,w,h,a)=>({label,x,y,w,h,...(a?{accent:true}:{})});
// Mismas secciones que hoy en /amigos, en las tres: solo cambia el diseño.
const base=(a)=>[R("añadir amigo + solicitudes",0,0,12,1),R("clasificación",0,1,12,3,a),R("semanal",0,4,6,2),R("mensual",6,4,6,2),R("tus amigos + comparar",0,6,6,2),R("retos entre amigos",6,6,6,2),R("platinar juntos",0,8,12,2)];
const opts=[
 {id:"marcador",label:"Marcador de estadio",kicker:"THE ROLL",thesis:"La clasificación como el marcador luminoso de un estadio: cifras grandes en LED, tu fila encendida, los demás bloques con el mismo lenguaje.",palette:["#050608","#0f1216","#7cc4e4","#ffcf3a","#e9eef7"],materials:["cifras de puntos luminosos","paneles negros con marco","tu fila iluminada"],viewport:"Arriba añadir amigo y solicitudes; el marcador de clasificación a lo ancho; debajo semanal/mensual como marcadores pequeños, y el resto (lista, retos, platinar juntos) en paneles del mismo estilo.",risk:"Si las cifras LED se abusan, cuesta leer los textos: solo en números.",wireframe:{cols:12,rows:10,regions:base(true)}},
 {id:"hoja",label:"Hoja de liga deportiva",thesis:"Como la tabla de una liga de fútbol en el periódico: podio arriba, tabla con posición, puntos y tendencia, secciones con cabecera de sección deportiva.",palette:["#0a0d13","#10151f","#7cc4e4","#e2b53e","#b9c2cc"],materials:["podio de tres","tabla con tendencia ▲▼ dibujada","cabeceras de sección"],viewport:"Podio de los tres primeros arriba de la clasificación; semanal y mensual como tablas pequeñas; lista de amigos con su racha.",risk:"La más cercana a lo que hay: cambio notable pero no radical.",wireframe:{cols:12,rows:10,regions:base(true)}},
 {id:"pizarra",label:"Pizarra de vestuario",thesis:"Tu grupo de amigos como la pizarra del vestuario: tiza, flechas y nombres escritos; retos y platinar juntos como jugadas dibujadas.",palette:["#16211b","#1f2c24","#e9eef7","#ffcf3a","#7cc4e4"],materials:["textura de pizarra","trazo de tiza","flechas a mano"],viewport:"Mismas secciones sobre fondo de pizarra: clasificación como lista escrita, retos como jugadas con flechas entre avatares.",risk:"Estilo muy marcado; la letra de tiza solo en títulos para no perder legibilidad.",wireframe:{cols:12,rows:10,regions:base(true)}},
];
fs.writeFileSync('.impeccable/rondas/08b-amigos.json',JSON.stringify({title:"Amigos (8/10) · otra tanda",question:"Misma pantalla y mismas funciones; solo cambia el diseño. Elige uno.",options:opts,reroll:true,steer:true,followup:true},null,2));
console.log('ok');
