const fs=require('fs');
const R=(label,x,y,w,h,a)=>({label,x,y,w,h,...(a?{accent:true}:{})});
const opts=[
 {id:"refinado",label:"Panel de control refinado",kicker:"THE ROLL",thesis:"Los mismos ajustes (General, Apariencia, Vitrinas y firma, Seguridad, Cuentas, Ocultar) con menú lateral fijo, grupos con título claro y vista previa pequeña junto a cada cambio visual.",palette:["#0a0d13","#10151f","#7cc4e4","#d7eef8","#e2b53e"],materials:["menú lateral con icono","grupos con separador","mini vista previa al lado"],viewport:"Menú lateral a la izquierda; a la derecha el grupo activo con sus opciones y, en Apariencia/perfil, una vista previa pequeña que cambia al momento.",risk:"Es la evolución natural de lo que hay: ordenado y claro, poco espectacular.",wireframe:{cols:12,rows:10,regions:[R("menú de ajustes",0,0,3,10),R("grupo de opciones",3,0,6,10,1),R("vista previa",9,0,3,5,1)]}},
 {id:"interruptores",label:"Tablero de interruptores",thesis:"Los ajustes como un panel físico: interruptores y selectores grandes agrupados por zonas (apariencia, privacidad, qué se oculta, avisos), todo a la vista.",palette:["#0c0f14","#161b23","#7cc4e4","#ffcf3a","#4ec98a"],materials:["interruptores grandes con estado","zonas con placa de título","luz de estado encendido/apagado"],viewport:"Una rejilla de zonas: cada zona una placa con sus interruptores; el estado se lee de un vistazo por las luces.",risk:"Con muchos ajustes la rejilla es larga; hay que agrupar muy bien.",wireframe:{cols:12,rows:10,regions:[R("apariencia",0,0,6,5,1),R("privacidad del perfil",6,0,6,5,1),R("ocultar",0,5,6,5),R("avisos",6,5,6,5)]}},
 {id:"taquilla",label:"Taquilla de personalización",thesis:"Lo visual del perfil (marcos, banners, títulos, efectos del nombre, paletas) como objetos en una taquilla: los desbloqueados a la vista, los bloqueados con candado y nivel necesario.",palette:["#0a0d13","#141b28","#7cc4e4","#e2b53e","#c07b4a"],materials:["objetos en casillas","candado con nivel","perfil en vivo al lado"],viewport:"A la izquierda la taquilla con pestañas por tipo de objeto; a la derecha tu perfil en vivo con lo que te pones. Seguridad, privacidad y Ocultar siguen en su menú, con el mismo estilo.",risk:"Solo transforma la parte de apariencia; el resto de ajustes se restyla sin tanta metáfora.",wireframe:{cols:12,rows:10,regions:[R("pestañas: marcos, banners, títulos, efectos, paletas",0,0,7,1),R("taquilla de objetos",0,1,7,9,1),R("tu perfil en vivo",7,0,5,10,1)]}},
];
fs.writeFileSync('.impeccable/rondas/10b-personalizacion.json',JSON.stringify({title:"Personalización (10/10) · otra tanda",question:"Mismos ajustes que hoy (apariencia, ocultar, privacidad, cómo se ve tu perfil); solo cambia el diseño.",options:opts,reroll:true,steer:true},null,2));
console.log('ok');
