const fs = require("fs");
const R = (label, x, y, w, h, accent) => ({ label, x, y, w, h, ...(accent ? { accent: true } : {}) });
const card = (id, label, thesis, materials, viewport, risk, regions, extra = {}) => ({ id, label, thesis, palette: extra.palette ?? ["#0a0d13", "#10151f", "#7cc4e4", "#d7eef8", "#e2b53e"], materials, viewport, risk, wireframe: { cols: 12, rows: 10, regions }, ...extra });
const opciones = [
  card("consola", "Cada una en su casa", "Cada página se viste con el idioma de su plataforma sin copiarlo: PlayStation como la pantalla de inicio de la consola (fila de baldosas sobre arte a pantalla completa), Xbox como su panel de mosaicos, Steam como su tienda de cápsulas, Epic como su escaparate negro de portadas grandes.", ["arte de fondo del juego elegido", "baldosas/mosaicos/cápsulas según plataforma", "color de marca como luz, no como pintura"], "Arriba, el juego destacado de esa plataforma a pantalla completa con una fila de baldosas para cambiarlo; debajo, sus secciones (noticias, tendencia, más jugados, lanzamientos y lo propio: PS Plus, ofertas, Game Pass, gratis) en el formato de esa casa.", "Cuatro diseños distintos que mantener; hay que evocar, nunca imitar marcas y logotipos al detalle.", [R("arte del destacado a pantalla completa", 0, 0, 12, 4, 1), R("fila de baldosas", 0, 3, 12, 1, 1), R("lo propio (PS Plus / ofertas / Game Pass / gratis)", 0, 4, 7, 3), R("tendencia y más jugados", 7, 4, 5, 3), R("noticias", 0, 7, 7, 3), R("lanzamientos", 7, 7, 5, 3)], { kicker: "THE ROLL", palette: ["#00439c", "#107c10", "#1b2838", "#121212", "#e9eef7"] }),
  card("tablero", "Tablero de la plataforma", "Las cuatro páginas comparten un mismo tablero de control, cada una con su color: arriba las cifras de la comunidad en esa plataforma (cazadores, horas, platinos del mes) y debajo módulos como en la cabina del Panel.", ["cifras grandes de la comunidad", "módulos con bisel", "color de marca en filetes y cifras"], "Banda con logo y tres cifras reales de Paragon en esa plataforma; debajo, rejilla de módulos: lo propio de la plataforma grande, tendencia, más jugados, lanzamientos y noticias.", "Las cifras dependen de la actividad real: con pocos usuarios en Epic o Xbox quedarán bajas.", [R("banda + cifras de la comunidad", 0, 0, 12, 2, 1), R("lo propio de la plataforma", 0, 2, 8, 4, 1), R("tendencia", 8, 2, 4, 4), R("más jugados", 0, 6, 4, 4), R("lanzamientos", 4, 6, 4, 4), R("noticias", 8, 6, 4, 4)]),
  card("revista", "Número especial de revista", "Cada plataforma es un número especial de revista: portada con su color y titular, sumario, y las secciones como reportajes a doble página.", ["portada a todo color", "sumario numerado", "reportajes con titular grande"], "Portada con el color y el logo de la plataforma y el titular del mes (la noticia principal); al lado el sumario; debajo, reportajes: lo propio (PS Plus, ofertas...), tendencia, más jugados y lanzamientos.", "Más lectura que exploración; las listas largas quedan mejor como tabla que como reportaje.", [R("portada", 0, 0, 8, 5, 1), R("sumario", 8, 0, 4, 5), R("reportaje: lo propio", 0, 5, 12, 2, 1), R("tendencia", 0, 7, 6, 3), R("más jugados + lanzamientos", 6, 7, 6, 3)]),
];
fs.writeFileSync(".impeccable/rondas/13-plataformas.json", JSON.stringify({ title: "Páginas de plataforma (13)", question: "PlayStation, Xbox, Steam y Epic: mismas secciones y datos (noticias, recomendados, tendencia, más jugados, lanzamientos, PS Plus, ofertas y jugadores de Steam, Game Pass, gratis de Epic); solo cambia el diseño. Elige uno.", options: opciones, reroll: true, steer: true, followup: true }, null, 2));
console.log("ok");
