// Genera .impeccable/rondas/NN-<seccion>.json para la página de decisión (serve-question).
const fs = require("fs");
const PAL = ["#0a0d13", "#10151f", "#7cc4e4", "#d7eef8", "#e2b53e"];
const R = (label, x, y, w, h, accent) => ({ label, x, y, w, h, ...(accent ? { accent: true } : {}) });
const card = (id, label, thesis, materials, viewport, risk, regions, extra = {}) => ({
  id, label, thesis, palette: extra.palette ?? PAL, materials, viewport, risk,
  wireframe: { cols: 12, rows: 10, regions }, ...extra,
});
const rondas = [
  ["panel", "Panel", "Lo primero que ves al entrar.", [
    card("constelacion", "Constelación", "Tu biblioteca como un cielo: cada juego es una estrella que brilla más cuanto más cerca estás del platino.", ["estrellas con halo por metal", "líneas entre juegos del mismo estudio", "fondo nocturno"], "El cielo ocupa la pantalla; la estrella más brillante (tu platino más cercano) está en el centro con su tarjeta abierta al lado.", "Bonito pero menos directo para leer números; necesita una lista alternativa.", [R("cabecera", 0, 0, 12, 1), R("cielo de juegos", 0, 1, 8, 7, 1), R("tarjeta del juego elegido", 8, 1, 4, 5, 1), R("liga y retos", 8, 6, 4, 2), R("actividad reciente", 0, 8, 12, 2)], { kicker: "THE ROLL" }),
    card("cabina", "Cabina de widgets", "Un panel de módulos que ordenas y redimensionas: cada cazador monta el suyo.", ["módulos con asa de arrastre", "rejilla visible al editar", "tamaños S/M/L"], "Rejilla de módulos: siguiente platino grande, liga, retos, racha y lanzamientos; botón 'Editar panel'.", "Si nadie lo personaliza, el orden por defecto tiene que ser muy bueno.", [R("cabecera", 0, 0, 12, 1), R("siguiente platino (L)", 0, 1, 8, 4, 1), R("liga (S)", 8, 1, 4, 2), R("racha (S)", 8, 3, 4, 2), R("retos (M)", 0, 5, 6, 3), R("lanzamientos (M)", 6, 5, 6, 3), R("editar panel", 0, 8, 12, 2)]),
    card("mision", "Misión del día", "Arriba, tres objetivos concretos para hoy calculados de tu biblioteca y tus rivales.", ["tres casillas grandes con progreso", "sello al completar", "el resto del panel debajo"], "Tres misiones de hoy en fila ('2 trofeos de God of War', 'adelanta a Israel', 'mantén la racha'), debajo el panel de siempre.", "Si las misiones son genéricas se ignoran; tienen que salir de tus datos reales.", [R("cabecera", 0, 0, 12, 1), R("misión 1", 0, 1, 4, 3, 1), R("misión 2", 4, 1, 4, 3, 1), R("misión 3", 8, 1, 4, 3, 1), R("siguiente platino", 0, 4, 7, 4), R("liga", 7, 4, 5, 4), R("actividad", 0, 8, 12, 2)]),
  ]],
  ["perfil", "Perfil", "Tu página pública.", [
    card("carta", "Carta holográfica", "Tu perfil es una carta coleccionable con brillo que se gira: delante lo que presumes, detrás los números.", ["foil holográfico platino", "borde por nivel", "reverso con estadísticas"], "Carta grande centrada que gira con el ratón; al lado tus platinos recientes y la vitrina.", "El giro no puede esconder la información: el reverso también tiene que leerse sin girar en móvil.", [R("cabecera", 0, 0, 12, 1), R("carta (anverso/reverso)", 3, 1, 6, 6, 1), R("platinos recientes", 0, 7, 6, 3), R("insignias", 6, 7, 6, 3)], { kicker: "THE ROLL" }),
    card("linea", "Línea de vida", "Toda tu carrera de cazador en una cronología vertical: primer trofeo, cada platino, récords, ligas ganadas.", ["eje vertical con años", "hitos grandes y pequeños", "saltos de año marcados"], "Cabecera compacta con nivel y cifras; debajo, la línea con los hitos alternando a los lados.", "Con poca historia queda corta; necesita buen estado vacío.", [R("cabecera + cifras", 0, 0, 12, 2, 1), R("eje", 5, 2, 2, 8), R("hito", 0, 3, 5, 2), R("hito", 7, 5, 5, 2), R("hito", 0, 7, 5, 2)]),
    card("vitrina", "Vitrina de coleccionista", "Tus platinos como medallas acuñadas en estantes iluminados; las insignias en cajas expositoras.", ["medallas de metal con relieve", "estantes con luz cenital", "cartelas con fecha"], "Nombre y nivel arriba; la vitrina ocupa el centro con las medallas; debajo las insignias.", "Muchos platinos = muchos estantes; necesita agrupar por año o plataforma.", [R("cabecera", 0, 0, 12, 2), R("estante de medallas", 0, 2, 12, 3, 1), R("estante de medallas", 0, 5, 12, 2, 1), R("insignias en cajas", 0, 7, 12, 3)]),
  ]],
  ["biblioteca", "Biblioteca", "Todos tus juegos.", [
    card("lomos", "Lomos de caja", "Una estantería de lomos verticales como cajas de juego: altura según horas, color según el metal alcanzado.", ["lomos con el logo del juego", "franja de metal", "caja que sale al tocarla"], "Estantería a lo ancho con los lomos ordenados; al tocar uno sale la caja con su progreso.", "Los lomos estrechos cuestan de leer en móvil: allí pasan a filas.", [R("filtros", 0, 0, 12, 1), R("estante de lomos", 0, 1, 12, 3, 1), R("estante de lomos", 0, 4, 12, 3, 1), R("caja abierta del juego", 3, 7, 6, 3)], { kicker: "THE ROLL" }),
    card("estantes", "Estantes por estado", "Carátulas agrupadas en baldas: casi platino, a medias, empezados, parados y platinados.", ["carátulas con barra de progreso", "baldas con título", "desplazamiento horizontal"], "Una balda por estado, la de 'casi platino' la primera; cada balda se desliza en horizontal.", "Con muchos juegos por estado, las baldas largas esconden cosas.", [R("filtros", 0, 0, 12, 1), R("casi platino", 0, 1, 12, 2, 1), R("a medias", 0, 3, 12, 2), R("empezados", 0, 5, 12, 2), R("platinados", 0, 7, 12, 3)]),
    card("tabla", "Tabla densa", "Una hoja de datos ordenable y filtrable para ver toda la biblioteca de golpe.", ["columnas fijas", "cifras tabulares", "barras de progreso finas"], "Tabla a lo ancho con carátula pequeña, progreso, horas, rareza y plataforma; filtros arriba.", "Fría: pierde las carátulas como protagonistas.", [R("filtros y columnas", 0, 0, 12, 1), R("tabla", 0, 1, 12, 9, 1)]),
  ]],
  ["juego", "Ficha de juego", "La página de cada juego.", [
    card("guia", "Guía de estrategia", "Como una guía impresa: checklist por capítulos, perdibles en rojo, notas al margen y casillas que se tachan.", ["papel de guía con márgenes", "casillas de verificación", "notas al margen"], "Portada del juego arriba; debajo la checklist por capítulos con los perdibles marcados y tus notas al lado.", "Tiene que seguir pareciendo la app y no un PDF.", [R("portada del juego", 0, 0, 12, 3), R("capítulos", 0, 3, 3, 7), R("checklist de trofeos", 3, 3, 6, 7, 1), R("notas al margen", 9, 3, 3, 7)], { kicker: "THE ROLL" }),
    card("consola", "Lista estilo consola", "Filas grandes con la foto de cada trofeo, rareza como barra, perdibles marcados y la ruta óptima uniendo los trofeos.", ["fila grande por trofeo", "barra de rareza", "línea de ruta"], "Artwork del juego de fondo arriba con tu progreso; debajo la lista grande estilo PS5.", "Es la más cercana a lo que hay ahora.", [R("artwork + progreso", 0, 0, 12, 3, 1), R("lista de trofeos", 0, 3, 8, 7, 1), R("ruta y perdibles", 8, 3, 4, 7)]),
    card("mapa", "Mapa de ruta", "Los trofeos como nodos de un mapa conectados en el orden recomendado.", ["nodos por metal", "caminos entre trofeos", "zonas bloqueadas"], "El mapa ocupa el centro; ves por dónde vas y qué se bloquea si te saltas un perdible.", "Hay juegos sin orden claro; ahí el mapa aporta poco.", [R("cabecera del juego", 0, 0, 12, 2), R("mapa de nodos", 0, 2, 9, 8, 1), R("trofeo seleccionado", 9, 2, 3, 8)]),
  ]],
  ["comunidad", "Comunidad", "Lo que hace la gente.", [
    card("stories", "Stories", "Arriba, círculos por persona con sus hitos del día; tocas y pasan como historias.", ["círculos con anillo del metal", "pantallas a pantalla completa", "barra de progreso de historias"], "Fila de stories arriba; debajo el feed de siempre.", "Formato muy de redes; puede sentirse ajeno.", [R("stories", 0, 0, 12, 2, 1), R("feed", 0, 2, 8, 8), R("destacados", 8, 2, 4, 8)], { kicker: "THE ROLL" }),
    card("radio", "En directo", "La comunidad como una emisión en vivo: lo que pasa ahora entra por arriba con su hora.", ["marca 'en directo'", "entradas con hora", "contador de actividad"], "Columna central que se va llenando sola; a la derecha quién está jugando ahora.", "Con poca actividad se ve vacía.", [R("en directo", 0, 0, 8, 10, 1), R("jugando ahora", 8, 0, 4, 5), R("tendencias", 8, 5, 4, 5)]),
    card("muro", "Muro de logros", "Los platinos grandes y a todo color; lo pequeño agrupado por persona y día.", ["tarjetas grandes para platinos", "resúmenes compactos", "reacciones flotando"], "Rejilla tipo muro con platinos grandes y resúmenes pequeños intercalados.", "Mezclar tamaños exige buen orden para que no parezca desordenado.", [R("platino grande", 0, 0, 6, 4, 1), R("resumen", 6, 0, 3, 2), R("resumen", 9, 0, 3, 2), R("platino grande", 6, 2, 6, 4, 1), R("resúmenes", 0, 4, 6, 3), R("más", 0, 7, 12, 3)]),
  ]],
  ["descubrir", "Descubrir", "Buscar el siguiente juego.", [
    card("matriz", "Matriz dificultad × horas", "Los juegos colocados en un plano: fácil a difícil, corto a largo. Eliges tu hueco.", ["plano con cuadrantes", "carátulas como puntos", "filtros por plataforma"], "El plano ocupa el centro; tocas una zona y sale la lista de juegos de ese cuadrante.", "Necesita datos de dificultad y horas de muchos juegos.", [R("filtros", 0, 0, 12, 1), R("plano dificultad × horas", 0, 1, 8, 9, 1), R("juegos del cuadrante", 8, 1, 4, 9)], { kicker: "THE ROLL" }),
    card("test", "Test de cazador", "Cinco preguntas rápidas y te recomienda juegos según cómo cazas.", ["preguntas a pantalla completa", "perfil de cazador resultante", "recomendaciones"], "Una pregunta grande cada vez; al final tu 'tipo de cazador' y sus juegos.", "Es un paso más antes de ver juegos.", [R("pregunta", 2, 1, 8, 5, 1), R("opciones", 2, 6, 8, 2), R("progreso", 2, 8, 8, 1)]),
    card("ruleta", "Ruleta", "Una ruleta con tu lista de deseados y pendientes que elige por ti el siguiente.", ["ruleta con carátulas", "filtros de duración", "animación de giro"], "La ruleta centrada; debajo el resultado con por qué te lo recomienda.", "Divertida pero poco seria como pantalla principal.", [R("ruleta", 3, 1, 6, 6, 1), R("resultado", 2, 7, 8, 3)]),
  ]],
  ["estadisticas", "Estadísticas y Wrap", "Tus números.", [
    card("calendario", "Calendario de calor", "Un año de actividad como calendario de calor: cada día su color según trofeos.", ["casillas por día", "escala de metal", "resumen del mes"], "El calendario a lo ancho arriba; debajo, al tocar un día, lo que conseguiste.", "Ya hay un mapa de actividad; tendría que ser el protagonista de verdad.", [R("calendario del año", 0, 0, 12, 4, 1), R("día elegido", 0, 4, 6, 3), R("resumen", 6, 4, 6, 3), R("gráficas", 0, 7, 12, 3)], { kicker: "THE ROLL" }),
    card("datos", "Datos en blanco y negro", "Todo en blanco y negro puro con un solo color para lo tuyo; trazos finos y números monoespaciados.", ["barras finas", "tipografía de datos", "un único color de acento"], "Cifras enormes arriba; debajo gráficas de trazo fino y tablas.", "Muy seca si no se cuida el ritmo.", [R("cifras grandes", 0, 0, 12, 3, 1), R("gráfica", 0, 3, 8, 4), R("tabla", 8, 3, 4, 7), R("gráfica", 0, 7, 8, 3)]),
    card("arbol", "Árbol de géneros", "Tus géneros y juegos como un árbol: las ramas más gruesas son lo que más juegas.", ["ramas por género", "hojas por juego", "grosor por horas"], "El árbol ocupa la pantalla; tocas una rama y ves sus juegos y cifras.", "Llamativo pero difícil de comparar números exactos.", [R("árbol", 0, 0, 8, 10, 1), R("rama elegida", 8, 0, 4, 10)]),
  ]],
  ["amigos", "Amigos", "Tu gente.", [
    card("lobby", "Lobby", "Como el lobby de una consola: quién está conectado, a qué juega y qué acaba de sacar.", ["avatares con estado", "juego actual", "invitar a sesión"], "Rejilla de amigos con su estado y juego; arriba los que están jugando ahora.", "Necesita saber quién está 'conectado' (hoy solo sabemos su última actividad).", [R("jugando ahora", 0, 0, 12, 3, 1), R("amigos", 0, 3, 8, 7), R("retos y clasificación", 8, 3, 4, 7)], { kicker: "THE ROLL" }),
    card("duelo", "Cara a cara", "Eliges un amigo y la pantalla se parte en dos: tú contra él, juego a juego.", ["pantalla partida", "barras enfrentadas", "marcador"], "Tú a la izquierda, tu amigo a la derecha, y entre ambos los juegos en común con barras enfrentadas.", "Solo compara de uno en uno.", [R("tú", 0, 0, 5, 3, 1), R("vs", 5, 0, 2, 3), R("amigo", 7, 0, 5, 3, 1), R("juegos en común", 0, 3, 12, 7)]),
    card("grafo", "Mapa de rivalidades", "Un grafo de quién adelanta a quién: flechas entre amigos según la liga de la semana.", ["nodos con avatar", "flechas de adelantamiento", "grosor por puntos"], "El grafo en el centro; tocas un amigo y ves vuestra rivalidad.", "Con pocos amigos el grafo es pobre.", [R("grafo", 0, 0, 8, 10, 1), R("rivalidad elegida", 8, 0, 4, 10)]),
  ]],
  ["paletas", "Paletas", "Colores de toda la app (además de las 6 ya añadidas).", [
    card("portada", "Paleta de tu juego favorito", "La app toma los colores de la carátula de tu juego favorito (ya tenemos el extractor de color de carátulas).", ["color sacado de la carátula", "acento y fondo derivados", "cambia al cambiar de favorito"], "En Apariencia, 'Desde mi juego': eliges el juego y ves la app teñida de sus colores.", "Algunas carátulas dan colores con poco contraste; hay que corregirlos automáticamente.", [R("selector de juego", 0, 0, 4, 10), R("vista previa de la app", 4, 0, 8, 10, 1)], { palette: ["#1a0f0a", "#c2410c", "#fcd34d", "#0f172a"] }),
    card("plataforma", "Paletas por plataforma", "Cuatro paletas oficiosas: PlayStation (azul), Xbox (verde), Steam (pizarra), Nintendo (rojo) con su fondo propio.", ["colores de marca suavizados", "fondo de cada plataforma", "logo discreto"], "Muestras grandes en Apariencia con el nombre de cada plataforma.", "Hay que no copiar la marca tal cual (derechos y parecido).", [R("PlayStation", 0, 0, 6, 5, 1), R("Xbox", 6, 0, 6, 5), R("Steam", 0, 5, 6, 5), R("Nintendo", 6, 5, 6, 5)], { palette: ["#0b1a3a", "#107c10", "#1b2838", "#e60012"] }),
    card("temporada", "Paleta de temporada", "Cada temporada del Pase trae su paleta (invierno, primavera…) y quien gana medalla la conserva.", ["paleta por trimestre", "desbloqueo por medalla", "fondo con motivo"], "En Temporada ves la paleta del trimestre; al ganar medalla aparece en Apariencia.", "Hay que diseñar una por trimestre.", [R("paleta de la temporada", 0, 0, 12, 5, 1), R("paletas ganadas", 0, 5, 12, 5)], { palette: ["#0c1624", "#8ecae6", "#ffb703", "#fb8500"] }),
  ]],
  ["personalizacion", "Personalización", "Lo que cada usuario puede ajustar.", [
    card("densidad", "Densidad y disposición", "Cómoda o compacta, orden de pestañas y panel por módulos: cada uno la app a su ritmo.", ["interruptor cómoda/compacta", "pestañas arrastrables", "módulos del panel"], "En Apariencia, vista previa en vivo mientras cambias densidad y orden.", "Más combinaciones que probar en cada pantalla.", [R("opciones", 0, 0, 4, 10), R("vista previa en vivo", 4, 0, 8, 10, 1)]),
    card("ambiente", "Ambiente", "Fondo con el artwork del juego que estás jugando, tema automático día/noche y sonido opcional al desbloquear.", ["artwork difuminado de fondo", "cambio automático por hora", "sonido de trofeo"], "Tres interruptores grandes con su vista previa.", "El fondo con artwork puede restar legibilidad; va muy difuminado.", [R("fondo con artwork", 0, 0, 6, 5, 1), R("día/noche", 6, 0, 6, 5), R("sonido", 0, 5, 12, 5)]),
    card("identidad", "Identidad del perfil", "Tu perfil más tuyo: carta con foil por nivel, marco animado, efecto del nombre y una canción o vídeo de fondo.", ["foil por nivel", "marcos y efectos ya existentes", "fondo animado"], "Editor del perfil con la carta en grande que cambia al momento.", "Cuidado con perfiles recargados; poner límites.", [R("editor", 0, 0, 5, 10), R("carta/perfil en vivo", 5, 0, 7, 10, 1)]),
  ]],
];
fs.mkdirSync(".impeccable/rondas", { recursive: true });
rondas.forEach(([id, titulo, sub, opciones], i) => {
  const payload = {
    title: `${titulo} (${i + 1}/${rondas.length})`,
    question: `${sub} Elige una estructura, o pide otra tanda.`,
    options: opciones,
    reroll: true,
    steer: true,
    followup: i < rondas.length - 1,
  };
  fs.writeFileSync(`.impeccable/rondas/${String(i + 1).padStart(2, "0")}-${id}.json`, JSON.stringify(payload, null, 2));
});
console.log(fs.readdirSync(".impeccable/rondas").join("\n"));
