// Rondas 11 y 12 (1 oct 2026): Noticias y el resto de Descubrir. Mismas funciones, solo diseño.
const fs = require("fs");
const PAL = ["#0a0d13", "#10151f", "#7cc4e4", "#d7eef8", "#e2b53e"];
const R = (label, x, y, w, h, accent) => ({ label, x, y, w, h, ...(accent ? { accent: true } : {}) });
const card = (id, label, thesis, materials, viewport, risk, regions, extra = {}) => ({
  id, label, thesis, palette: extra.palette ?? PAL, materials, viewport, risk,
  wireframe: { cols: 12, rows: 10, regions }, ...extra,
});
const rondas = [
  ["11-noticias", "Noticias (11/12)", "Mismas secciones (próximos lanzamientos, recién salidos, noticias de tus juegos, últimas noticias); solo cambia el diseño. Elige uno.", [
    card("salidas", "Panel de salidas", "Los lanzamientos como el panel de un aeropuerto: cada juego es un vuelo con su fecha y estado; las noticias, un teletipo.", ["filas de panel con letras de paleta", "estado: en hora / retrasado / salido", "teletipo de titulares"], "Arriba el panel de 'Próximas salidas' a lo ancho y 'Recién llegados' al lado; debajo las noticias de tus juegos destacadas y el resto como teletipo con hora y fuente.", "Las letras de paleta solo en fechas y estados; los títulos largos de juego se leen en letra normal.", [R("próximas salidas", 0, 0, 8, 4, 1), R("recién llegados", 8, 0, 4, 4), R("noticias de tus juegos", 0, 4, 12, 3, 1), R("teletipo de últimas noticias", 0, 7, 12, 3)], { kicker: "THE ROLL", palette: ["#0a0c10", "#13161c", "#ffcf3a", "#e9eef7", "#7cc4e4"] }),
    card("portada", "Portada de periódico", "Una portada de diario de cazadores: la noticia principal a lo grande, columnas con filetes y una agenda de lanzamientos en el lateral.", ["cabecera de cabecera de diario", "columnas y filetes", "agenda lateral"], "Noticia principal con imagen grande a la izquierda, agenda de lanzamientos en la columna derecha; debajo 'De tus juegos' como sección propia y el resto en columnas.", "Con noticias sin imagen buena la portada pierde fuerza; necesita un estado sin foto digno.", [R("noticia principal", 0, 0, 8, 4, 1), R("agenda de lanzamientos", 8, 0, 4, 7), R("de tus juegos", 0, 4, 8, 3, 1), R("últimas noticias en columnas", 0, 7, 12, 3)]),
    card("calendario", "Calendario de lanzamientos", "Los lanzamientos colocados en una línea de tiempo por semanas y meses; las noticias, un río a la derecha.", ["línea de tiempo con hoy marcado", "carátulas colgadas de su fecha", "río de noticias"], "Línea de tiempo horizontal arriba (lo ya salido a la izquierda de 'hoy', lo próximo a la derecha); debajo, noticias de tus juegos y últimas en dos columnas.", "Con muchas fechas juntas se amontona; agrupa por semana.", [R("línea de tiempo: salidos | hoy | próximos", 0, 0, 12, 4, 1), R("noticias de tus juegos", 0, 4, 5, 6, 1), R("últimas noticias", 5, 4, 7, 6)]),
  ]],
  ["12-descubrir", "Descubrir (12/12)", "El resto de Descubrir (destacados, buscador, plataformas, novedades, tendencias, joyas ocultas, recomendaciones), con la matriz ya hecha. Solo cambia el diseño.", [
    card("lista", "Lista de éxitos", "Descubrir como las listas de éxitos: el número 1 en portada, las tendencias como Top 10 con cifras enormes y flechas de subida, las novedades como 'nuevas entradas'.", ["numerales gigantes de posición", "flecha y +N de jugadores esta semana", "carátula junto a su puesto"], "Destacado grande como 'número 1'; Top 10 de tendencias en dos columnas con números enormes; novedades y joyas como listas secundarias; buscador y plataformas arriba compactos.", "Los números grandes ocupan sitio: en móvil el Top pasa a una columna.", [R("buscador + plataformas", 0, 0, 12, 1), R("número 1 (destacado)", 0, 1, 7, 4, 1), R("nuevas entradas", 7, 1, 5, 4), R("top 10 tendencias", 0, 5, 12, 3, 1), R("joyas ocultas", 0, 8, 12, 2)], { kicker: "THE ROLL" }),
    card("revista", "Revista de portada", "Una revista de videojuegos: portada con el destacado, índice de plataformas, reportajes por sección y 'Joyas' como reseñas con nota.", ["portada con titular grande", "índice numerado", "notas como sello de reseña"], "Portada a pantalla con el destacado y su titular; al lado el índice (plataformas); debajo secciones con cabecera de revista y las joyas con su nota en sello.", "Más lectura que exploración: hay que cuidar que se pueda curiosear rápido.", [R("portada (destacado)", 0, 0, 8, 5, 1), R("índice de plataformas", 8, 0, 4, 5), R("novedades", 0, 5, 12, 2), R("tendencias", 0, 7, 6, 3), R("joyas con nota", 6, 7, 6, 3, 1)]),
    card("escaparate", "Escaparate de tienda", "Como el escaparate de una tienda nocturna: carátulas en vitrinas iluminadas, pasillos por plataforma y etiquetas de precio que dicen por qué mirarlo.", ["vitrinas con luz cenital", "pasillos por plataforma", "etiquetas colgantes (+N jugadores, ★ nota)"], "Destacado en el escaparate principal; cada fila es una balda iluminada (novedades, tendencias, joyas); las plataformas son los pasillos arriba.", "Es la más cercana a lo que hay: mejora clara, menos sorpresa.", [R("pasillos (plataformas) + buscador", 0, 0, 12, 1), R("escaparate principal", 0, 1, 12, 4, 1), R("balda novedades", 0, 5, 12, 2), R("balda tendencias", 0, 7, 12, 2), R("balda joyas", 0, 9, 12, 1)]),
  ]],
];
for (const [archivo, title, question, options] of rondas) {
  fs.writeFileSync(`.impeccable/rondas/${archivo}.json`, JSON.stringify({ title, question, options, reroll: true, steer: true, followup: true }, null, 2));
}
console.log("ok");
