const fs = require("fs");
const R = (label, x, y, w, h, accent) => ({ label, x, y, w, h, ...(accent ? { accent: true } : {}) });
const card = (id, label, thesis, materials, viewport, risk, regions, extra = {}) => ({ id, label, thesis, palette: extra.palette ?? ["#0a0d13", "#10151f", "#7cc4e4", "#d7eef8", "#e2b53e"], materials, viewport, risk, wireframe: { cols: 12, rows: 10, regions }, ...extra });
const opciones = [
  card("manual", "Manual de instrucciones", "Como el librito que venía dentro de la caja del juego: un índice fijo a la izquierda y los ocho capítulos seguidos, para leer de corrido o saltar a uno.", ["índice lateral fijo con el capítulo activo", "capítulos con portadilla", "comandos de Discord como botones de mando"], "Índice a la izquierda (Vincular, Trofeos, Estadísticas...) que se marca al bajar; a la derecha cada capítulo con su título grande y sus apartados como párrafos con un icono, no tarjetas.", "Página larga: el índice fijo tiene que funcionar bien en móvil (pasa a una tira arriba).", [R("índice fijo", 0, 0, 3, 10), R("capítulo: portadilla", 3, 0, 9, 2, 1), R("apartados del capítulo", 3, 2, 9, 4), R("siguiente capítulo", 3, 6, 9, 4)], { kicker: "THE ROLL" }),
  card("ruta", "Ruta del cazador", "Cómo funciona contado como el recorrido de un cazador: de vincular la cuenta a competir en ligas, en etapas unidas por una línea, como la caza en 4 pasos de la portada.", ["línea de ruta que une las etapas", "etapa con número y estado", "atajo a la pantalla de cada cosa"], "Una línea vertical recorre las ocho etapas; cada una se despliega con sus apartados y un botón para ir a esa parte de la app.", "Algunas partes (notificaciones, perfil) no son una etapa sino ajustes: encajan peor en un recorrido.", [R("cabecera", 0, 0, 12, 1), R("etapa 1 abierta", 1, 1, 11, 3, 1), R("etapas siguientes", 1, 4, 11, 6), R("línea de ruta", 0, 1, 1, 9)]),
  card("ayuda", "Centro de ayuda", "Un centro de ayuda con buscador: escribes lo que buscas y filtra todos los apartados de golpe; las categorías son pestañas y cada respuesta se abre como acordeón.", ["buscador grande arriba", "categorías como chips", "preguntas que se despliegan"], "Buscador centrado arriba; debajo las ocho categorías como chips y la lista de apartados en acordeón, con el enlace a la pantalla dentro de cada uno.", "Añade el buscador (filtro en el propio navegador, sin cambiar contenidos); en acordeón se lee menos de un vistazo.", [R("buscador", 2, 0, 8, 2, 1), R("categorías", 0, 2, 12, 1), R("apartados en acordeón", 1, 3, 10, 7)]),
];
fs.writeFileSync(".impeccable/rondas/14-como-funciona.json", JSON.stringify({ title: "Cómo funciona (14)", question: "Mismo contenido (vincular, trofeos, estadísticas, backlog, comunidad, planificador, avisos y Discord, perfil); solo cambia el diseño. Elige uno.", options: opciones, reroll: true, steer: true, followup: true }, null, 2));
console.log("ok");
